project:
  repository: jmolivas/gatsby-casper
  type: gatsby
  status: active
  name: jmolivas/gatsby-casper
  buildStatus: ready
  external: false
  provider: github
  deployment:
    developmentCommand: gatsby develop
    productionBranch: master
    publishDirectory: public
    packager: npm
    contentDirectory:
      - src/content
    buildCommand: gatsby build
    builds:
      master:
        weight: 1
        id: _dcqnjp279
        environmentVariables: []
        branch: master
schemas:
  - type: dataset
    definitions:
      fields:
        - orderable: true
          removable: true
          system: false
          widget: text
          name: Id
          type: string
          required: true
          value: ''
          id: id
        - removable: true
          system: false
          widget: textarea
          name: Description
          type: string
          required: true
          value: ''
          id: description
          orderable: true
        - orderable: true
          removable: true
          system: false
          widget: MediaSchema
          name: Image
          type: string
          required: true
          value: ''
          id: image
      schema:
        id: tag
        name: Tag
    schema:
      json:
        required:
          - id
          - description
          - image
        type: object
        properties:
          id:
            title: Id
            default: ''
            type: string
          image:
            default: ''
            type: string
            title: Image
          description:
            title: Description
            default: ''
            type: string
      name: Tag
      ui:
        'ui:order':
          - id
          - description
          - image
          - '*'
        description:
          'ui:widget': textarea
        id:
          'ui:widget': text
        image:
          'ui:widget': MediaSchema
  - definitions:
      fields:
        - name: Name
          required: false
          type: string
          id: name
          widget: text
        - id: message
          widget: textarea
          name: Message
          required: false
          type: string
      schema:
        name: Contact
        id: contact
    schema:
      json:
        required: []
        type: object
        properties:
          name:
            default: ''
            type: string
            title: Name
          message:
            default: ''
            type: string
            title: Message
      name: Contact
      ui:
        name:
          'ui:widget': text
        'ui:order':
          - name
          - message
          - '*'
        message:
          'ui:widget': textarea
    type: form
  - definitions:
      schema:
        id: page
        name: Page
      fields:
        - value: ''
          id: title
          orderable: true
          removable: true
          system: false
          widget: text
          name: Title
          type: string
          required: true
        - orderable: true
          removable: true
          system: false
          widget: textarea
          name: Excerpt
          type: string
          required: true
          value: ''
          id: excerpt
        - value: ''
          id: content
          orderable: true
          removable: true
          system: false
          widget: SlateEditor
          name: Content
          type: string
          required: true
        - widget: MediaSchema
          name: Image
          type: string
          required: true
          value: ''
          id: image
          orderable: true
          removable: true
          system: false
        - value: ''
          id: date
          orderable: true
          removable: true
          system: false
          widget: DatePicker
          name: Date
          type: string
          required: true
        - removable: true
          system: false
          widget: text
          name: Author
          type: string
          required: true
          value: ''
          id: author
          orderable: true
        - name: Draft
          type: string
          required: true
          value: ''
          id: draft
          orderable: true
          removable: true
          system: false
          widget: text
        - name: Tags
          type: string
          required: true
          value: ''
          id: tags
          orderable: true
          removable: true
          system: false
          widget: text
    schema:
      json:
        required:
          - title
          - excerpt
          - content
          - image
          - date
          - author
          - draft
          - tags
        type: object
        properties:
          author:
            default: ''
            type: string
            title: Author
          excerpt:
            title: Excerpt
            default: ''
            type: string
          image:
            default: ''
            type: string
            title: Image
          content:
            default: ''
            type: string
            title: Content
          date:
            title: Date
            default: ''
            type: string
          tags:
            title: Tags
            default: ''
            type: string
          draft:
            default: ''
            type: string
            title: Draft
          title:
            title: Title
            default: ''
            type: string
      name: Page
      ui:
        author:
          'ui:widget': text
        excerpt:
          'ui:widget': textarea
        image:
          'ui:widget': MediaSchema
        'ui:order':
          - title
          - excerpt
          - content
          - image
          - date
          - author
          - draft
          - tags
          - '*'
        content:
          'ui:widget': SlateEditor
        date:
          'ui:widget': DatePicker
        tags:
          'ui:widget': text
        draft:
          'ui:widget': text
        title:
          'ui:widget': text
    type: content
  - definitions:
      fields:
        - orderable: true
          removable: true
          system: false
          widget: text
          name: Id
          type: string
          required: true
          value: ''
          id: id
        - orderable: true
          removable: true
          system: false
          widget: MediaSchema
          name: Avatar
          type: string
          required: true
          value: ''
          id: avatar
        - type: string
          required: true
          value: ''
          id: bio
          orderable: true
          removable: true
          system: false
          widget: textarea
          name: Bio
        - widget: text
          name: Facebook
          type: string
          required: true
          value: ''
          id: facebook
          orderable: true
          removable: true
          system: false
        - name: Location
          type: string
          required: true
          value: ''
          id: location
          orderable: true
          removable: true
          system: false
          widget: text
        - widget: MediaSchema
          name: Profile_image
          type: string
          required: true
          value: ''
          id: profile_image
          orderable: true
          removable: true
          system: false
        - name: Twiter
          type: string
          required: true
          value: ''
          id: twiter
          orderable: true
          removable: true
          system: false
          widget: text
        - widget: text
          name: Twitter
          type: string
          required: true
          value: ''
          id: twitter
          orderable: true
          removable: true
          system: false
        - name: Website
          type: string
          required: true
          value: ''
          id: website
          orderable: true
          removable: true
          system: false
          widget: text
      schema:
        name: Author
        id: author
    schema:
      json:
        required:
          - id
          - avatar
          - bio
          - facebook
          - location
          - profile_image
          - twiter
          - twitter
          - website
        type: object
        properties:
          website:
            default: ''
            type: string
            title: Website
          twitter:
            title: Twitter
            default: ''
            type: string
          facebook:
            default: ''
            type: string
            title: Facebook
          bio:
            default: ''
            type: string
            title: Bio
          profile_image:
            title: Profile_image
            default: ''
            type: string
          avatar:
            title: Avatar
            default: ''
            type: string
          id:
            default: ''
            type: string
            title: Id
          location:
            default: ''
            type: string
            title: Location
          twiter:
            default: ''
            type: string
            title: Twiter
      name: Author
      ui:
        avatar:
          'ui:widget': MediaSchema
        id:
          'ui:widget': text
        location:
          'ui:widget': text
        twiter:
          'ui:widget': text
        website:
          'ui:widget': text
        twitter:
          'ui:widget': text
        facebook:
          'ui:widget': text
        bio:
          'ui:widget': textarea
        'ui:order':
          - id
          - avatar
          - bio
          - facebook
          - location
          - profile_image
          - twiter
          - twitter
          - website
          - '*'
        profile_image:
          'ui:widget': MediaSchema
    type: dataset
mapping:
  content: []
  dataset: []
  form: []
