project:
  deployment:
    builds:
      master:
        branch: master
        weight: 1
        id: _dcqnjp279
        environmentVariables: []
    developmentCommand: gatsby develop
    productionBranch: master
    publishDirectory: public
    packager: npm
    contentDirectory:
      - src/content
    buildCommand: gatsby build
  repository: jmolivas/gatsby-casper
  type: gatsby
  status: active
  name: jmolivas/gatsby-casper
  buildStatus: ready
  external: false
  provider: github
schemas:
  - type: content
    definitions:
      schema:
        name: Page
        id: page
      fields:
        - removable: true
          system: false
          widget: text
          name: Title
          type: string
          required: true
          value: ''
          id: title
          orderable: true
        - removable: true
          system: false
          widget: textarea
          name: Excerpt
          type: string
          required: true
          value: ''
          id: excerpt
          orderable: true
        - value: ''
          id: content
          orderable: true
          removable: true
          system: false
          widget: SlateEditor
          name: Content
          type: string
          required: true
        - widget: MediaSchema
          name: Image
          type: string
          required: true
          value: ''
          id: image
          orderable: true
          removable: true
          system: false
        - type: string
          required: true
          value: ''
          id: date
          orderable: true
          removable: true
          system: false
          widget: DatePicker
          name: Date
        - type: string
          required: true
          value: ''
          id: author
          orderable: true
          removable: true
          system: false
          widget: text
          name: Author
        - value: ''
          id: draft
          orderable: true
          removable: true
          system: false
          widget: text
          name: Draft
          type: string
          required: true
        - orderable: true
          removable: true
          system: false
          widget: text
          name: Tags
          type: string
          required: true
          value: ''
          id: tags
    schema:
      ui:
        excerpt:
          'ui:widget': textarea
        image:
          'ui:widget': MediaSchema
        'ui:order':
          - title
          - excerpt
          - content
          - image
          - date
          - author
          - draft
          - tags
          - '*'
        content:
          'ui:widget': SlateEditor
        date:
          'ui:widget': DatePicker
        tags:
          'ui:widget': text
        draft:
          'ui:widget': text
        title:
          'ui:widget': text
        author:
          'ui:widget': text
      json:
        properties:
          author:
            title: Author
            default: ''
            type: string
          excerpt:
            default: ''
            type: string
            title: Excerpt
          image:
            title: Image
            default: ''
            type: string
          content:
            default: ''
            type: string
            title: Content
          date:
            title: Date
            default: ''
            type: string
          tags:
            default: ''
            type: string
            title: Tags
          draft:
            title: Draft
            default: ''
            type: string
          title:
            title: Title
            default: ''
            type: string
        required:
          - title
          - excerpt
          - content
          - image
          - date
          - author
          - draft
          - tags
        type: object
      name: Page
