project:
  status: active
  name: jmolivas/gatsby-casper
  buildStatus: ready
  external: false
  provider: github
  deployment:
    buildCommand: gatsby build
    builds:
      master:
        weight: 1
        id: _dcqnjp279
        environmentVariables: []
        branch: master
    developmentCommand: gatsby develop
    productionBranch: master
    publishDirectory: public
    packager: npm
    contentDirectory:
      - src/content
  repository: jmolivas/gatsby-casper
  type: gatsby
schemas:
  - type: dataset
    definitions:
      fields:
        - orderable: true
          removable: true
          system: false
          widget: text
          name: Id
          type: string
          required: true
          value: ''
          id: id
        - widget: MediaSchema
          name: Avatar
          type: string
          required: true
          value: ''
          id: avatar
          orderable: true
          removable: true
          system: false
        - type: string
          required: true
          value: ''
          id: bio
          orderable: true
          removable: true
          system: false
          widget: textarea
          name: Bio
        - removable: true
          system: false
          widget: text
          name: Facebook
          type: string
          required: true
          value: ''
          id: facebook
          orderable: true
        - value: ''
          id: location
          orderable: true
          removable: true
          system: false
          widget: text
          name: Location
          type: string
          required: true
        - orderable: true
          removable: true
          system: false
          widget: MediaSchema
          name: Profile_image
          type: string
          required: true
          value: ''
          id: profile_image
        - orderable: true
          removable: true
          system: false
          widget: text
          name: Twiter
          type: string
          required: true
          value: ''
          id: twiter
        - widget: text
          name: Twitter
          type: string
          required: true
          value: ''
          id: twitter
          orderable: true
          removable: true
          system: false
        - orderable: true
          removable: true
          system: false
          widget: text
          name: Website
          type: string
          required: true
          value: ''
          id: website
      schema:
        name: Author
        id: author
    schema:
      json:
        required:
          - id
          - avatar
          - bio
          - facebook
          - location
          - profile_image
          - twiter
          - twitter
          - website
        type: object
        properties:
          twitter:
            title: Twitter
            default: ''
            type: string
          facebook:
            title: Facebook
            default: ''
            type: string
          bio:
            title: Bio
            default: ''
            type: string
          profile_image:
            title: Profile_image
            default: ''
            type: string
          avatar:
            title: Avatar
            default: ''
            type: string
          id:
            title: Id
            default: ''
            type: string
          location:
            default: ''
            type: string
            title: Location
          twiter:
            title: Twiter
            default: ''
            type: string
          website:
            default: ''
            type: string
            title: Website
      name: Author
      ui:
        twitter:
          'ui:widget': text
        facebook:
          'ui:widget': text
        bio:
          'ui:widget': textarea
        'ui:order':
          - id
          - avatar
          - bio
          - facebook
          - location
          - profile_image
          - twiter
          - twitter
          - website
          - '*'
        profile_image:
          'ui:widget': MediaSchema
        avatar:
          'ui:widget': MediaSchema
        id:
          'ui:widget': text
        location:
          'ui:widget': text
        twiter:
          'ui:widget': text
        website:
          'ui:widget': text
  - type: dataset
    definitions:
      schema:
        id: tag
        name: Tag
      fields:
        - value: ''
          id: id
          orderable: true
          removable: true
          system: false
          widget: text
          name: Id
          type: string
          required: true
        - widget: textarea
          name: Description
          type: string
          required: true
          value: ''
          id: description
          orderable: true
          removable: true
          system: false
        - orderable: true
          removable: true
          system: false
          widget: MediaSchema
          name: Image
          type: string
          required: true
          value: ''
          id: image
    schema:
      json:
        required:
          - id
          - description
          - image
        type: object
        properties:
          description:
            title: Description
            default: ''
            type: string
          id:
            default: ''
            type: string
            title: Id
          image:
            title: Image
            default: ''
            type: string
      name: Tag
      ui:
        id:
          'ui:widget': text
        image:
          'ui:widget': MediaSchema
        'ui:order':
          - id
          - description
          - image
          - '*'
        description:
          'ui:widget': textarea
  - type: form
    definitions:
      fields:
        - name: Name
          required: false
          type: string
          id: name
          widget: text
        - widget: textarea
          name: Message
          required: false
          type: string
          id: message
      schema:
        name: Contact
        id: contact
    schema:
      json:
        required: []
        type: object
        properties:
          name:
            default: ''
            type: string
            title: Name
          message:
            title: Message
            default: ''
            type: string
      name: Contact
      ui:
        'ui:order':
          - name
          - message
          - '*'
        message:
          'ui:widget': textarea
        name:
          'ui:widget': text
  - type: content
    definitions:
      schema:
        name: Page
        id: page
      fields:
        - name: Title
          type: string
          required: true
          value: ''
          id: title
          orderable: true
          removable: true
          system: false
          widget: text
        - type: string
          required: true
          value: ''
          id: excerpt
          orderable: true
          removable: true
          system: false
          widget: textarea
          name: Excerpt
        - type: string
          required: true
          value: ''
          id: content
          orderable: true
          removable: true
          system: false
          widget: SlateEditor
          name: Content
        - removable: true
          system: false
          widget: MediaSchema
          name: Image
          type: string
          required: true
          value: ''
          id: image
          orderable: true
        - orderable: true
          removable: true
          system: false
          widget: DatePicker
          name: Date
          type: string
          required: true
          value: ''
          id: date
        - widget: text
          name: Author
          type: string
          required: true
          value: ''
          id: author
          orderable: true
          removable: true
          system: false
        - orderable: true
          removable: true
          system: false
          widget: text
          name: Draft
          type: string
          required: true
          value: ''
          id: draft
        - type: string
          required: true
          value: ''
          id: tags
          orderable: true
          removable: true
          system: false
          widget: text
          name: Tags
    schema:
      json:
        required:
          - title
          - excerpt
          - content
          - image
          - date
          - author
          - draft
          - tags
        type: object
        properties:
          excerpt:
            default: ''
            type: string
            title: Excerpt
          image:
            title: Image
            default: ''
            type: string
          content:
            title: Content
            default: ''
            type: string
          date:
            title: Date
            default: ''
            type: string
          tags:
            default: ''
            type: string
            title: Tags
          draft:
            title: Draft
            default: ''
            type: string
          title:
            default: ''
            type: string
            title: Title
          author:
            default: ''
            type: string
            title: Author
      name: Page
      ui:
        excerpt:
          'ui:widget': textarea
        image:
          'ui:widget': MediaSchema
        'ui:order':
          - title
          - excerpt
          - content
          - image
          - date
          - author
          - draft
          - tags
          - '*'
        content:
          'ui:widget': SlateEditor
        date:
          'ui:widget': DatePicker
        tags:
          'ui:widget': text
        draft:
          'ui:widget': text
        title:
          'ui:widget': text
        author:
          'ui:widget': text
