project:
  type: gatsby
  status: active
  name: jmolivas/gatsby-casper
  buildStatus: ready
  external: false
  provider: github
  deployment:
    contentDirectory:
      - src/content
    buildCommand: gatsby build
    builds:
      master:
        id: _dcqnjp279
        environmentVariables: []
        branch: master
        weight: 1
    developmentCommand: gatsby develop
    productionBranch: master
    publishDirectory: public
    packager: npm
schemas:
  - definitions:
      fields:
        - required: false
          type: string
          id: name
          widget: text
          name: Name
        - widget: textarea
          name: Message
          required: false
          type: string
          id: message
      schema:
        name: Contact
        id: contact
    schema:
      ui:
        'ui:order':
          - name
          - message
          - '*'
        message:
          'ui:widget': textarea
        name:
          'ui:widget': text
      json:
        required: []
        type: object
        properties:
          message:
            default: ''
            type: string
            title: Message
          name:
            default: ''
            type: string
            title: Name
      name: Contact
    type: form
  - type: content
    definitions:
      fields:
        - orderable: true
          removable: true
          system: false
          widget: text
          name: Title
          type: string
          required: true
          value: ''
          id: title
        - type: string
          required: false
          value: ''
          id: excerpt
          orderable: true
          removable: true
          system: false
          widget: textarea
          name: Excerpt
        - removable: true
          system: false
          widget: SlateEditor
          name: Content
          type: string
          required: true
          value: ''
          id: content
          orderable: true
        - removable: true
          system: false
          widget: MediaSchema
          name: Image
          type: string
          required: true
          value: ''
          id: image
          orderable: true
        - removable: true
          system: false
          widget: DatePicker
          name: Date
          type: string
          required: true
          value: ''
          id: date
          orderable: true
        - orderable: true
          removable: true
          system: false
          widget: text
          name: Author
          type: string
          required: true
          value: ''
          id: author
        - widget: checkbox
          name: Draft
          required: false
          type: boolean
          id: draft
      schema:
        id: page
        name: Page
    schema:
      ui:
        author:
          'ui:widget': text
        excerpt:
          'ui:widget': textarea
        image:
          'ui:widget': MediaSchema
        'ui:order':
          - title
          - excerpt
          - content
          - image
          - date
          - author
          - draft
          - '*'
        content:
          'ui:widget': SlateEditor
        date:
          'ui:widget': DatePicker
        draft:
          'ui:widget': checkbox
        title:
          'ui:widget': text
      json:
        required:
          - title
          - content
          - image
          - date
          - author
        type: object
        properties:
          author:
            title: Author
            default: ''
            type: string
          excerpt:
            title: Excerpt
            default: ''
            type: string
          image:
            title: Image
            default: ''
            type: string
          content:
            title: Content
            default: ''
            type: string
          date:
            default: ''
            type: string
            title: Date
          draft:
            title: Draft
            default: ''
            type: boolean
          title:
            default: ''
            type: string
            title: Title
      name: Page
  - type: dataset
    definitions:
      schema:
        name: Author
        id: author
      fields:
        - orderable: true
          removable: true
          system: false
          widget: text
          name: Id
          type: string
          required: true
          value: ''
          id: id
        - name: Avatar
          type: string
          required: true
          value: ''
          id: avatar
          orderable: true
          removable: true
          system: false
          widget: MediaSchema
        - name: Bio
          type: string
          required: true
          value: ''
          id: bio
          orderable: true
          removable: true
          system: false
          widget: textarea
        - orderable: true
          removable: true
          system: false
          widget: text
          name: Facebook
          type: string
          required: true
          value: ''
          id: facebook
        - removable: true
          system: false
          widget: text
          name: Location
          type: string
          required: true
          value: ''
          id: location
          orderable: true
        - name: Profile_image
          type: string
          required: true
          value: ''
          id: profile_image
          orderable: true
          removable: true
          system: false
          widget: MediaSchema
        - orderable: true
          removable: true
          system: false
          widget: text
          name: Twiter
          type: string
          required: true
          value: ''
          id: twiter
        - type: string
          required: true
          value: ''
          id: twitter
          orderable: true
          removable: true
          system: false
          widget: text
          name: Twitter
        - widget: text
          name: Website
          type: string
          required: true
          value: ''
          id: website
          orderable: true
          removable: true
          system: false
    schema:
      json:
        required:
          - id
          - avatar
          - bio
          - facebook
          - location
          - profile_image
          - twiter
          - twitter
          - website
        type: object
        properties:
          website:
            default: ''
            type: string
            title: Website
          twitter:
            title: Twitter
            default: ''
            type: string
          facebook:
            title: Facebook
            default: ''
            type: string
          bio:
            default: ''
            type: string
            title: Bio
          profile_image:
            default: ''
            type: string
            title: Profile_image
          avatar:
            title: Avatar
            default: ''
            type: string
          id:
            title: Id
            default: ''
            type: string
          location:
            title: Location
            default: ''
            type: string
          twiter:
            title: Twiter
            default: ''
            type: string
      name: Author
      ui:
        avatar:
          'ui:widget': MediaSchema
        id:
          'ui:widget': text
        location:
          'ui:widget': text
        twiter:
          'ui:widget': text
        website:
          'ui:widget': text
        twitter:
          'ui:widget': text
        facebook:
          'ui:widget': text
        bio:
          'ui:widget': textarea
        'ui:order':
          - id
          - avatar
          - bio
          - facebook
          - location
          - profile_image
          - twiter
          - twitter
          - website
          - '*'
        profile_image:
          'ui:widget': MediaSchema
  - type: dataset
    definitions:
      fields:
        - orderable: true
          removable: true
          system: false
          widget: text
          name: Id
          type: string
          required: true
          value: ''
          id: id
        - widget: textarea
          name: Description
          type: string
          required: true
          value: ''
          id: description
          orderable: true
          removable: true
          system: false
        - name: Image
          type: string
          required: true
          value: ''
          id: image
          orderable: true
          removable: true
          system: false
          widget: MediaSchema
      schema:
        name: Tag
        id: tag
    schema:
      json:
        required:
          - id
          - description
          - image
        type: object
        properties:
          image:
            title: Image
            default: ''
            type: string
          description:
            default: ''
            type: string
            title: Description
          id:
            title: Id
            default: ''
            type: string
      name: Tag
      ui:
        'ui:order':
          - id
          - description
          - image
          - '*'
        description:
          'ui:widget': textarea
        id:
          'ui:widget': text
        image:
          'ui:widget': MediaSchema
mapping:
  content:
    - schema: page
      path: src/content/google-spreadsheet-manage-content.md
    - schema: page
      path: src/content/great-catsby.md
    - schema: page
      path: src/content/welcome.md
    - schema: page
      path: src/content/using-gatsby.md
    - schema: page
      path: src/content/how-run-puppeteer-headless-chrome.md
    - schema: page
      path: src/content/a-full-style-test.md
    - schema: page
      path: src/content/gatsby-wax.md
  dataset:
    - schema: tag
      path: src/content/tag.yaml
    - schema: author
      path: src/content/author.yaml
  form: []
